version: 1
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "monthly"
      time: "15:00"
      timezone: "Asia/Hong_Kong"
    open-pull-requests-limit: 0
      
